### ISSUE TITLE
Add syntax highlighting for YAML

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#10]
CodeApprove doesn't have syntax highlighting for YAML, which makes it a bit harder to review:

![image](https://user-images.githubusercontent.com/7783288/179052308-2cf6bc90-b952-4aa0-85b0-63b2cbbd774d.png)

Github for comparison:

![image](https://user-images.githubusercontent.com/7783288/179052425-a3a84d3b-f11c-4d5a-9347-3cc6c1c7e029.png)

**Comment by hatboysam** [comment]
YAML support is live!
![image](https://user-images.githubusercontent.com/997280/179171232-aba9f5bb-4e85-47c3-aadf-688ac86e1cea.png)
