### ISSUE TITLE
Images added via GitHub are not rendered properly

### ISSUE THREAD

**Issue by jwngr** [codeapprove/feedback#100]
**Repro steps:**
1. Create a PR from GitHub
2. Add any image
3. Submit PR

**Expected:** CodeApprove displays that image properly

**Actual:** CodeApprove displays broken images (see below)

### Screenshots
<img width="832" alt="Screenshot - 2023-05-31 at 11-47-23@2x" src="https://github.com/codeapprove/feedback/assets/4149793/856722cc-a4a8-4424-bdda-44ca7de41af0">
<img width="1078" alt="Screenshot - 2023-05-31 at 11-45-18@2x" src="https://github.com/codeapprove/feedback/assets/4149793/4cb38076-065c-4c88-9241-0d0eeab31c19">
<img width="1081" alt="Screenshot - 2023-05-31 at 11-45-23@2x" src="https://github.com/codeapprove/feedback/assets/4149793/af9d1803-4fea-4a4a-a7bb-044a6707852e">

**Comment by samatcodeapprove** [comment]
@jwngr thanks for reporting this. Seems like GitHub has changed their image URLs? IIRC they used to be on `githubusercontent.com` but now they seem to be stored under a repo-specific path. I'll dig.

----

**Edit** Ah yeah confirmed, GitHub made a breaking change here:
https://github.blog/changelog/2023-05-09-more-secure-private-attachments/

**Comment by samatcodeapprove** [comment]
@jwngr this is now fixed, although what I did was a bit of a hack (GitHub did not think this change through, IMO) so I am not 100% sure it will keep working forever! Definitely flag if you see anything broken like this in the future.

**Comment by jwngr** [comment]
Seems to be working again - thanks!
