### ISSUE TITLE
Show file contents for file moves

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#102]
When we move a file without changing its contents, it seems like CodeApprove doesn't offer any way of viewing the file contents:

![image](https://github.com/codeapprove/feedback/assets/7783288/1556d4ce-2f76-4e2a-a37e-10aae38deb63)

Github's diff has a similar problem, but you can click "View file" to see the contents.

It would be helpful if CodeApprove had a mechanism to view the file contents of a moved file without leaving the CodeApprove UI.

**Comment by samatcodeapprove** [comment]
@mtlynch deploying this feature now! When a text-based file has been moved with no changes you should now be able to click to load the whole file. Commenting on the loaded file should work as normal.

**Comment by mtlynch** [comment]
Great, thanks!
