### ISSUE TITLE
GIFs on CodeApprove don't appear on Github

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#105]
We had a [confusing exchange](https://codeapprove.com/pr/tiny-pilot/tinypilot/1589) recently because one of my teammates commented on CodeApprove with a GIF:

![image](https://github.com/codeapprove/feedback/assets/7783288/b4210208-fe0d-4fb0-92c0-f7c0b46c0680)

But when the comment was mirrored to Github, there was no GIF or indication of a GIF:

![image](https://github.com/codeapprove/feedback/assets/7783288/f8efa059-f896-430f-88a0-d60a78897e42)

So, I was confused because the comment didn't make sense without the GIF as context.

It's obviously not super important, but it would be good to either make sure the GIF translates to the Github-echo'ed comments or to indicate in the Github version that a GIF is missing from the comment.

**Comment by samatcodeapprove** [comment]
@mtlynch uhhh in what world is a hackerman gif **not** important? P0!

(but really, I would expect this to work and I don't think it'll be a hard fix)

**Comment by mtlynch** [comment]
Haha, thanks, @samatcodeapprove I appreciate it!

**Comment by samatcodeapprove** [comment]
@mtlynch actually I think this was somehow specific to that GIF! Here's a test I did directly on GitHub:
https://github.com/codeapprove/meta/issues/35

That Hackerman gif does not render, but the (excellent) gif of the Raptors mascot falling renders fine with very similar markup.

GitHub does some weird things to the Markdown and generates an `<animated-image>` tag where the Hackerman gif points to this URL:
https://camo.githubusercontent.com/a477b27ff52cb1d20777fad6cbfd6810b979008ca84439c9c0ea0d8ce2916dcd/68747470733a2f2f692e696d6775722e636f6d2f706c4a476e43622e676966

When I click that URL I get "Content Length Exceeded". I'll report this to GitHub but I don't think there's much more I can do!

**Comment by mtlynch** [comment]
Ah, thanks for checking into it!
