### ISSUE TITLE
CodeApprove badge not appearing on a PR

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#108]
We're having trouble getting CodeApprove to add a badge on a private repo PR:

https://github.com/tiny-pilot/microsd-integrity-check/pull/30

I tried disabling / re-adding the repo to the CodeApprove Github app, but it didn't seem to have an effect. I also tried adding the label `codeapprove`, but no effect.

I am able to construct the CodeApprove review URL manually:

https://codeapprove.com/pr/tiny-pilot/microsd-integrity-check/30

**Comment by jotaen4tinypilot** [comment]
Some more data points here:

I tried to manually construct the review URL manually before (`https://codeapprove.com/pr/tiny-pilot/microsd-integrity-check/30`), but that resulted in a 404. In contrast to @mtlynch, I don’t have admin permissions on the repo, however, so it may have to do something with this?

I can reproduce the 404 in [another PR (#28)](https://github.com/tiny-pilot/microsd-integrity-check/pull/28) of that same repo, which also misses the badge. So when going to https://codeapprove.com/pr/tiny-pilot/microsd-integrity-check/28, I get a redirect to https://codeapprove.com/404.

**Comment by jotaen4tinypilot** [comment]
I was able to produce a link by adding the `codeapprove` label to the PR beforehand (manually). So without that label, I got the 404. After adding the label, it worked. The badge button (“Review on CodeApprove”) was automatically added after I added the `codeapprove` label.

**Comment by mtlynch** [comment]
@samatcodeapprove - Any updates here? We're still seeing this issue.

**Comment by samatcodeapprove** [comment]
@mtlynch sorry somehow this issue slipped past my Gmail filters, I will take a look!

**Comment by samatcodeapprove** [comment]
@mtlynch @jotaen4tinypilot in Settings for the repo in question do you have the auto-create reviews setting enabled?
<img width="950" alt="Screenshot 2024-02-14 at 8 33 26 PM" src="https://github.com/codeapprove/feedback/assets/109921904/88df2047-7793-4a2c-abb0-386e6fb9aa98">

From what I can see in the database you have that setting enabled on _many_ of your repos, but not the one we're talking about here (`microsd-integrity-check`).

Without that setting, the review is only created when the `codeapprove` label is manually added on GitHub.

(Btw: to navigate to a CodeAppove review directly from GitHUb you can just replace `github.com` with `codeapprove.com` in your URL bar and everything should work)

**Comment by mtlynch** [comment]
@samatcodeapprove - Ah, it was off. Thanks!

Is it off by default when adding a repo? I don't recall disabling it, and my expectation is that the setting would be enabled by default.

**Comment by samatcodeapprove** [comment]
Yeah it's off by default right now, because for new users the ability to try CodeApprove one PR at a time makes onboarding low risk. 

I'm happy to make this an org-wide setting so that you can set it and forget it though.

**Comment by mtlynch** [comment]
>I'm happy to make this an org-wide setting so that you can set it and forget it though.

That would be handy!

**Comment by samatcodeapprove** [comment]
Deploying a new version of the Settings page now which allows the "auto review" setting to be enabled at the org level.

**Comment by mtlynch** [comment]
@samatcodeapprove - Excellent, thanks!
