### ISSUE TITLE
Shortcuts shortcut not working

### ISSUE THREAD

**Issue by ioanfuse** [codeapprove/feedback#109]
<img width="209" alt="image" src="https://github.com/codeapprove/feedback/assets/141632085/bb6e30e5-4a96-428a-bc74-188850af28ce">

Shift + / doesn't do anything. Also tried clicking on the button to see shortcuts, also doesn't do anything. Am I missing something?

**Comment by samatcodeapprove** [comment]
@ioanfuse thanks for reporting! It does seem like there's a regression there (Shift+/ didn't work for me). However clicking on that button while on a review page _does_ work for me.

In the meantime, here's a screenshot of the shortcuts:
<img width="582" alt="image" src="https://github.com/codeapprove/feedback/assets/109921904/547bfea5-5c6c-482b-b03f-972551811e75">

**Comment by samatcodeapprove** [comment]
@ioanfuse deploying the fix for this now! Thanks for reporting. If you have any more feedback, please let me know (and don't forget you can invite your coworkers from the Settings page)
