### ISSUE TITLE
CodeApprove pops scary warning about losing data on reload even when everything is saved

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#11]
I'm acting as the author on a review, and I'm responding to my reviewer's feedback with CodeApprove comments. When I push my commits, CodeApprove prompts me to reload, but when I click the button to reload, it warns me that I have unsaved changes:

![image](https://user-images.githubusercontent.com/7783288/179773173-2842baa8-f0de-4a68-bc87-4d2107765694.png)

But all of pending comments are saved. I've already hit the "Add to Review" button on all of them, so the warning seems erroneous.

If #8 is fixed, this issue goes away "for free."

**Comment by samatcodeapprove** [comment]
This dialog is gone 👋
