### ISSUE TITLE
Line preview is illegible in dark mode

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#110]
Thanks for adding light mode (#96)!

I think a small side-effect is that the line preview is mostly illegilble in dark mode:

![image](https://github.com/codeapprove/feedback/assets/7783288/2b9a95b5-dc7c-4c58-9a78-50f08f59b571)

**Comment by samatcodeapprove** [comment]
@mtlynch thanks for filing this! Seems like an issue with how code themes are loading in dark mode in production, not happening in development. I will take a look.

**Comment by samatcodeapprove** [comment]
@mtlynch ok the general issue with theme loading should be fixed now! It was a Webpack thing. Still don't love how those single-line previews look in _light_ mode but it's a lot better.

**Comment by mtlynch** [comment]
@samatcodeapprove - Fix confirmed. Thanks!
