### ISSUE TITLE
Dragging and dropping to upload files fails with `InvalidCharacterError`

### ISSUE THREAD

**Issue by jwngr** [codeapprove/feedback#111]
All file uploads failling with this error:

![Screenshot - 2024-04-16 at 11 -02-43@2x](https://github.com/codeapprove/feedback/assets/4149793/99861aee-feba-442e-ae30-218e0bff9de7)

Just trying to add a screenshot to a new discussion item on a review.

Repros on latest Edge, haven't tested elsewhere

**Comment by jwngr** [comment]
A few more details here:
* This happens when **dragging and dropping** a screenshot into a discussion. I swear this used to work for me, but it now fails when I try on both Edge and Safari.
* Uploading via the image icon works fine
* My coworker Tanishq is also unable to drag and drop a screenshot into a discussion. He says it has been broken for months. He's on Chrome.
* Jonny is successfully **able** to drag and drop on Chrome.
* The error above seems to be a Sentry error. It's possible the real error is getting swallowed by your Sentry logging. I don't see anything else in the logs but this error message doesn't make sense to me.

**Comment by samatcodeapprove** [comment]
@jwngr sorry this one somehow missed my inbox! Sounds like a clear bug, I'll take a look as soon as I can.

**Comment by samatcodeapprove** [comment]
Huh it looks like macOS now puts a NBSP unicode character in Screenshot file names! TIL
<img width="535" alt="Screenshot 2024-04-20 at 1 45 36 PM" src="https://github.com/codeapprove/feedback/assets/109921904/5e449abb-4827-4c9f-9cd8-b9a15594c3af">

Anyway I should have been handling this from the start, I will get a fix in ASAP.

**Comment by samatcodeapprove** [comment]
Fix deploying now! Sorry again for letting this one slip through my filters.
