### ISSUE TITLE
Minor request: Make `Resolve` toggle default state to be disabled by default when replying to a comment

### ISSUE THREAD

**Issue by adlrocha** [codeapprove/feedback#118]
Hey, Sam. Finisterra Labs team back again with a small request if you think it makes sense.

We have an internal policy on PR reviews where the commenter is the one responsible for resolving the review comment when it has been successfully addressed. However, the current behavior when replying comments (where the `Resolve` toggle is automatically set when commenting) is leading to some of us to unintentionally resolving comments when replying to them (without it having been fully addressed). 

Would it be possible to make the `Resolve` initial state to be disabled, and for the reviewer to have to explicitly mark the `Resolve`  toggle or click `Resolved`  after commenting to mark the comment as resolved. This would be of huge help for us, hopefully we don't break things for other. Let me know if you need any follow-up.

We really appreciate your support, as always. Cheers!

**Comment by samatcodeapprove** [comment]
@adlrocha I'm happy to make this into a repository setting. I've had other users feel strongly in exactly the opposite way so I can't change it globally. Adding this setting should be an easy fix!

Also (shameless plug) I also run https://gitguard.dev which is a tool to help you enforce any other policies you might have around PRs.

**Comment by adlrocha** [comment]
> @adlrocha I'm happy to make this into a repository setting.

This would be perfect. Thanks!

> Also (shameless plug) I also run https://gitguard.dev/ which is a tool to help you enforce any other policies you might have around PRs.

Will definitely look deeper into this. Cheers!

**Comment by samatcodeapprove** [comment]
@adlrocha I am pushing a new build with this feature right now. If you go to the Settings page and expand your org under "Installations" you'll see a new toggle for each repo "Resolve threads by default?" which should default to true.

If you disable this, then the "Resolved" toggle will no longer default to being on for comment replies on that repository. Hopefully this solves your issue!

<img width="950" alt="Screenshot 2024-09-07 at 9 50 36 PM" src="https://github.com/user-attachments/assets/ae7c8a0f-7e83-4483-8573-2820e4825de0">

**Comment by adlrocha** [comment]
Amazing. Thank you!
