### ISSUE TITLE
View preferences reset on page reload

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#13]
If I specify view settings for the review (e.g., which files are open, which commit is the base), those settings reset on page reload.

Before reload:

![image](https://user-images.githubusercontent.com/7783288/179776586-2e8a7576-9895-48a6-aa48-d78d500c70aa.png)

After reload:

![image](https://user-images.githubusercontent.com/7783288/179776848-46fe3306-5dcd-48fa-b933-1226c275aefc.png)

It would be nice if CodeApprove persisted the view across page reloads.

**Comment by hatboysam** [comment]
Great idea and that should be a pretty simple addition!

**Comment by hatboysam** [comment]
Request from @codingcanuck: also include diff order in this.

**Comment by samatcodeapprove** [comment]
@mtlynch rolling out a new build with this now! Right now I'm storing the sort order, base commit, and head commit between reloads via URL params. If this is useful and manageable I can expand this to other state too.
