### ISSUE TITLE
Can't scroll around when a comment is too big for the comment box

### ISSUE THREAD

**Issue by hatboysam** [codeapprove/feedback#19]
Can't use trackpad to scroll vertically or horizontally in a comment that's too large to fit in the draft comment box
You can make a too-wide comment by pasting a long URL like https://github.com/protocolbuffers/protobuf/blob/aa22c5e0de189b74271335eea179e5321d88768e/src/google/protobuf/repeated_ptr_field.h#L1248

(reported by @codingcanuck)

**Comment by samatcodeapprove** [comment]
This is no longer an issue.
