### ISSUE TITLE
Offer a fun LGTM stamp

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#23]
This is a silly feature request, and I've given it before over email, but I'm creating a bug for easy tracking.

We were discussing CodeApprove in our dev team meeting today discussing what we'd need to transition from Reviewable to CodeApprove, and one of the developers lamented giving up Reviewable's LGTM stamp. We all agreed that it was a small thing but it makes the LGTM experience very satisfying.

![image](https://user-images.githubusercontent.com/7783288/181099864-4ef18756-9249-4ecb-bdac-2705a4070af6.png)

We'd love to see a similar feature in CodeApprove.

**Comment by samatcodeapprove** [comment]
> We were discussing CodeApprove in our dev team meeting today discussing what we'd need to transition from Reviewable to CodeApprove

This is quite a carrot for me! I have a feeling I can convince the bosses at CodeApprove to add a stamp 😉

**Comment by samatcodeapprove** [comment]
Consider this request ... approved!
<img width="159" alt="github-stamp-allbg-2x" src="https://user-images.githubusercontent.com/109921904/182027287-b2b767e5-5d48-4c4e-ab8e-00d52e9d9b37.png">

**Comment by mtlynch** [comment]
Awesome, thanks!
