### ISSUE TITLE
Opening a PR triggers a notification

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#25]
CodeApprove generates a bit of email/notification noise because it adds a comment to a PR announcing that the PR:

![image](https://user-images.githubusercontent.com/7783288/181102438-f15c803c-6663-45fa-a1d8-09fbde4f81d9.png)

If you have email notifications enabled, it means an extra email to everyone on the PR which isn't actionable, as CodeApprove being available doesn't necessarily make the PR ready for review. If CodeApprove is configured to add itself to every PR in a repo, it means getting an extra notification as soon as the PR opens.

My preference would be for CodeApprove to just edit the top-level comment with a link rather than adding its own comment and triggering a notification.

**Comment by samatcodeapprove** [comment]
@mtlynch I love the idea of editing the PR description instead! Thanks for the tip, I’ll probably do that.

**Comment by samatcodeapprove** [comment]
@mtlynch rolling this out now. You should see this fun new badge at the bottom of your PR description as soon as the PR is added to CodeApprove:

![github-tag-allbg](https://user-images.githubusercontent.com/109921904/181371150-a9910ad2-2d09-4bdc-a838-287bb0709818.png)

**Comment by mtlynch** [comment]
Looks great! Thanks!
