### ISSUE TITLE
Won't let me upload a .mov file

### ISSUE THREAD

**Issue by berlinjohnson** [codeapprove/feedback#26]
I took a screen recording with the native quicktime tool on a mac (cmd+shift+5) but it wouldn't let me upload the .mov file to my comment 😞 🎞️

**Comment by samatcodeapprove** [comment]
@berlinjohnson fancy seeing you on this repo! I think this will be a simple fix.

**Comment by samatcodeapprove** [comment]
Support for `.mov` files is rolling out now!
