### ISSUE TITLE
Sort files in lexicographic order in diff view

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#29]
CodeApprove is choosing an odd display order for files in my diff. I'm not sure what ordering it's using or if it's just random:

![image](https://user-images.githubusercontent.com/7783288/182683375-2b88fafc-f6c5-4fba-bbee-607161811feb.png)

### Github

Github orders by absolute path, and it doesn't distinguish between files in subfolders or at the same folder level as long as the absolute path is earlier:

![image](https://user-images.githubusercontent.com/7783288/182683511-12a70c00-f624-4e9a-a9b3-b528ec6f1638.png)

### My preference

My preferred ordering is:

1. Files within a folder, in lexicographic order
2. Subfolders, in lexicographic order

For example:

```text
./a.go
./b.go
./f.go
./c/d.go
./c/e.go
```

So even though `f` is after `c`, it still appears first because files within the directory take precedence over files in any subfolders.

### Reviewable

Reviewable's ordering seems to line up with my preferred ordering:

![image](https://user-images.githubusercontent.com/7783288/182684138-d19d227b-ba42-4bad-8c72-f00fe8d7b7a3.png)

**Comment by samatcodeapprove** [comment]
@mtlynch this is a great explanation and should be something I can fix pretty easily. 
For the screenshot above, what diff order do you have selected in CodeApprove? Is that the file path order, or is it ordered by descending number of lines changed?

**Comment by mtlynch** [comment]
@samatcodeapprove - Oh, I didn't even realize there was a sort option. I had it as the default, which I guess is `diff (desc)`. 

File path is closer to what I expect, except that I'd like to see all files in a folder before any subfolders and for `foo.go` to appear before `foo_test.go`.

![image](https://user-images.githubusercontent.com/7783288/182852984-0e52ae04-a48c-4a88-bc51-dbdfad87001f.png)

**Comment by samatcodeapprove** [comment]
@mtlynch deploying a build with better sorting now! I think it's exactly what you asked for but let me know if it's not quite right.
