### ISSUE TITLE
CodeApprove deletes top-level comment draft without warning

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#30]
(Don't worry - I didn't lose any data due to this. I sort of guessed this would be the behavior, and I saved my comments before trying it)

I use the PR-level comment for high-level discussion, and sometimes those comments can be long and inline parts of the PR description. I sometimes bounce back and forth between making high-level comments at the PR-level and line-level comments in the diff.

CodeApprove doesn't seem to offer a way to save the PR-level comment. Worse, if you close the window for the PR-level comment, CodeApprove deletes your comment without warning:

https://user-images.githubusercontent.com/7783288/182685641-556a07c2-d306-4199-98fc-364210a6f08c.mp4

Related: #8

**Comment by samatcodeapprove** [comment]
Yikes! Yes that's definitely a bug and I am not sure how I didn't notice it before.

**Comment by samatcodeapprove** [comment]
Ok I just deployed a fix here so that this text is preserved even if you open/close the dialog. It's still not preserved if you actually navigate away from the page, that's a larger project I want to do for all comment fields.

**Comment by mtlynch** [comment]
@samatcodeapprove - Nice, I just used this feature today!
