### ISSUE TITLE
Show changes since last review hides threads

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#32]
I'm currently author on a review. My reviewer sent me his first round of feedback, which included 7 notes:

* 1 PR-level comment 
* 5 line-level comments (unresolved)
* 1 line-level comment (resolved) - It was an optional note

![image](https://user-images.githubusercontent.com/7783288/182950445-4c966c22-71df-4a18-854f-ea6bc3add319.png)

If I set the view to "Show: all changes," I can see all the comments.

![image](https://user-images.githubusercontent.com/7783288/182950389-0b5283f2-6e29-42d4-88cc-486409ecc27e.png)

If I change the view to "Show since review by *reviewer*", the PR-level comment and the resolved line-level comment disappear:

![image](https://user-images.githubusercontent.com/7783288/182951031-b4ac83c6-1920-49ce-b7ad-480cc0d0b344.png)

This caught me by surprise, as I'd like to respond explicitly to all the notes in a review.

**Comment by samatcodeapprove** [comment]
@mtlynch this feels like a bug to me!

**Comment by samatcodeapprove** [comment]
Also @mtlynch just to be clear on what the bug is exactly: you chose "since review X" and some of the comments in review X were no longer visible?

**Comment by mtlynch** [comment]
>you chose "since review X" and some of the comments in review X were no longer visible?

Yes, exactly. It removed the the line-level comment that the reviewer had marked as resolved because it was optional and the PR-level comment.

**Comment by samatcodeapprove** [comment]
Deploying a change now which should fix this, please let me know if it's still not showing you the expected threads when using "view since".
