### ISSUE TITLE
Be able to assign reviewers and assignees when creating a PR

### ISSUE THREAD

**Issue by rockwotj** [codeapprove/feedback#33]
I use https://codeapprove.com/create to create PRs and I can't assign reviewers or cc folks until the PR is created. This is annoying in a manner of ways, mostly that creating a PR is quite slow (3-10 seconds, I'm assuming you're creating it with the label and waiting for the webhook to call you back) and it's a long enough pause in my workflow that I decided to file this task.

Is the answer that I should just start using GitHub to open my PRs?

**Comment by samatcodeapprove** [comment]
That seems like a good improvement, I could add reviewers/cc's to the PR creation page. Thanks for letting me know you're using it!

**Comment by samatcodeapprove** [comment]
@rockwotj I am pushing out a build with support for this now!

**Comment by rockwotj** [comment]
Thanks Sam! You're the man!
