### ISSUE TITLE
Sort dotfiles first in filename order view

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#34]
Thanks for improving the file sort order in #29! That matches my desired sorting, though it behaves unexpectedly with dotfiles or folders with leading dot:

![image](https://user-images.githubusercontent.com/7783288/183437775-a662897d-6715-4afe-873a-5175558c361f.png)

### Current behavior

* `bundler/create-bundle`
* `bundler/verify-bundle`
* `.circleci/config.yml`
* `bundler/.gitignore`
* `bundler/bundle/ansible.cfg`

### Desired behavior

Most tools (Github, VS Code, bash) seem to sort dotfiles and dotfolders first, so I'd prefer this ordering:

* `.circleci/config.yml` (moved to first position)
* `bundler/.gitignore` (moved to second position)
* `bundler/create-bundle`
* `bundler/verify-bundle`
* `bundler/bundle/ansible.cfg`

**Comment by samatcodeapprove** [comment]
@mtlynch yep that's a bug. As always thank you for the extremely actionable feedback!

**Comment by samatcodeapprove** [comment]
Deploying a fix for this now!

**Comment by mtlynch** [comment]
@samatcodeapprove  I think there's been a regression here, as the `.circleci` path is now appearing out of order:

![image](https://user-images.githubusercontent.com/7783288/188742017-59dc63dd-5c60-4507-a56a-a56539408739.png)

**Comment by samatcodeapprove** [comment]
Ah thanks for flagging this! Those files without extensions (`bundler/create-bundle`) were breaking my sort. Pushing a fix for this now.

**Comment by mtlynch** [comment]
Verified, thanks!
