### ISSUE TITLE
Add :pray or :thanks for 🙏🏽 

### ISSUE THREAD

**Issue by tstirrat** [codeapprove/feedback#36]
🙏🏽 is hard to get from autocomplete in CA. It's `:pray` in GitHub, but I have no idea how to get it in CA

<img width="274" alt="Screen Shot 2022-08-09 at 2 50 04 PM" src="https://user-images.githubusercontent.com/702990/183768010-2d3d2be1-4f25-40b3-b1fa-4a61721aeade.png">

<img width="231" alt="Screen Shot 2022-08-09 at 2 50 29 PM" src="https://user-images.githubusercontent.com/702990/183768110-405f298b-243d-417f-a323-ae079d08bd67.png">

<img width="217" alt="Screen Shot 2022-08-09 at 2 50 36 PM" src="https://user-images.githubusercontent.com/702990/183768097-c3c86bad-25fd-40b1-856a-be00d721af7f.png">

**Comment by samatcodeapprove** [comment]
Deploying support for `:pray:` and `:thanks:` mapping to 🙏 now!
