### ISSUE TITLE
Assignee toggling woes

### ISSUE THREAD

**Issue by rockwotj** [codeapprove/feedback#37]
There are times when I am reviewing a PR and there is a discussion on the PR that causes it to no longer be my turn to review. It's really a lot of mouse clicks to remove myself as assigned and add the author as the assignee. It's also doubly annoying because the action seems to be delayed and doesn't happen immediately. To make it worse when the delayed action happens it often closes the menu as I'm trying to pick out the author.

I'd love the action here was immediate, or even better there was a "it's not my turn button" (I think critique had this?) that did these steps automatically.

**Comment by samatcodeapprove** [comment]
@rockwotj pushing a build now to make this much more immediate in the case where you're removing yourself as the only assignee. In that case it will get instantly assigned to the author.
