### ISSUE TITLE
Prioritize prefix matches before substring matches in user picker

### ISSUE THREAD

**Issue by jwngr** [codeapprove/feedback#47]
I do this **all the time** since we had a new person join the team causing this conflict. Leads to actual real world inefficiencies since I keep assigning the wrong person and the person I wanted to assign the PR to isn't even aware the PR exists. I notice a day later after wondering why the review hasn't happened yet.

**Scenario:**
* Teammate A is called "Bobby Tables"
* Teammate B is called "Alice Thingamabob"
* I do `@bob` in a comment or `bob` in the "Reviewer" field

**Expected:** `Bobby Tables` is the top suggestion since it's a prefix match

**Actual:** `Alice Thingamabob` is the top suggestion since she comes first alphabetically (or maybe it's just random based on some internal ID?)

**Comment by samatcodeapprove** [comment]
👍 this is a good improvement!

**Comment by samatcodeapprove** [comment]
Deploying a new build to fix this now! Should be live in ~6 minutes.

**Comment by jwngr** [comment]
Works great, thank you 🙏
