### ISSUE TITLE
Can’t open review when coming from Github

### ISSUE THREAD

**Issue by jotaen4tinypilot** [codeapprove/feedback#48]
From time to time, I’m unable to access the CodeApprove review when clicking on the link/button in a Github review.

<img width="938" alt="Screenshot 2022-08-26 at 18 47 12" src="https://user-images.githubusercontent.com/83721279/186953506-01209abf-d380-45f5-853a-68cb215a0d48.png">

In the address bar, I can see that it opens the correct URL for the CodeApprove review, but then it redirects me to the following page, and I’m stuck there forever while the progress bar keeps spinning.

<img width="796" alt="Screenshot 2022-08-26 at 18 44 39" src="https://user-images.githubusercontent.com/83721279/186953327-af90e1bd-16e1-4489-bcdf-a9c89ca1dac2.png">

This only happens erratically, so most of the time (like 9 out of 10 times) it all works fine, but then it’s broken all of a sudden. After some time, it starts to work again, without me having done anything.

I’m using CodeApprove with this very Github account. I’m on MacOS 12.2 + Chrome 104.

**Comment by samatcodeapprove** [comment]
@jotaen4tinypilot thanks for reporting this! I should be able to find the error in my logs and see why this is happening to you.

**Comment by samatcodeapprove** [comment]
@jotaen4tinypilot has this happened recently? I have not heard any other reports ... if it's working better for you now we can close this but if not I am happy to leave it open.

**Comment by jotaen4tinypilot** [comment]
No, I can’t recall it happening since then, so I think we can close.
