### ISSUE TITLE
Difficult to scroll text in top-level comment

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#50]
If you leave a top-level comment that's long enough to not fit within the text area, it's difficult to scroll up and down. There's no vertical scrollbar, and the mouse scrollwheel has no effect (it scrolls the entire page instead of the text area). The only way I've found to scroll up and down is with keyboard arrow keys.

![image](https://user-images.githubusercontent.com/7783288/187245847-b48e61d5-7657-4f62-b63d-05ba81508c0f.png)

**Comment by samatcodeapprove** [comment]
Thanks for reporting! Just to make sure we're on the same page, here's what I see:
https://www.loom.com/share/587cc18f006b4dda841b1187d6a3be9e

When text is entered that's larger than the initial text area, the box grows with the text. The issue arises when the box is bigger than the whole viewport. In that situation, there is no way to scroll down.

**Comment by mtlynch** [comment]
>When text is entered that's larger than the initial text area, the box grows with the text. The issue arises when the box is bigger than the whole viewport. In that situation, there is no way to scroll down.

Oh, no, I was seeing something different. In my screen, the text area didn't grow with the text. I'm not sure why, and I can't reproduce it, but you can see in my screenshot that there was text above the visible part of the text area:

![image](https://user-images.githubusercontent.com/7783288/187289607-4f26ee79-b5c3-444c-9851-e4bb6f74d654.png)

I can't reproduce it now, so I'll reopen if I hit it again.
