### ISSUE TITLE
Comment thread duplicated within file

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#51]
I ran into a strange issue today where a single comment I left as a reviewer now appears in two different places in the file with the same response from the author in both.

This happens in both split and unified diff views:

![image](https://user-images.githubusercontent.com/7783288/187433686-a8c7f3d0-3068-4eb8-852d-ae3524ef7b0b.png)

**Comment by samatcodeapprove** [comment]
That's very strange! Never seen that before. Would you mind giving me the PR number and the repo? You could email it if you're not comfortable sharing.

**Comment by mtlynch** [comment]
Sure, it's https://github.com/tiny-pilot/tinypilotkvm.com/pull/813

We're still working on that PR, so things might shift around, but as of this writing, the dupe is still showing up for me.

**Comment by samatcodeapprove** [comment]
I just deployed a workaround for this, it should be live if you do a hard refresh and you should not see this comment in two places anymore. Thanks for reporting and definitely let me know if you see something else like this in the future!
