### ISSUE TITLE
Reply contents don't sync across views

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#52]
I just ran into a behavior in CodeApprove that confused me few a few moments.

I'm reviewer on a PR and I've done a round of reviews and the author has replied. One of the threads appears both in the "Comments" section at the bottom and inline in the code. I added a reply, then edited my reply before publishing my notes. A few minutes later, I re-read the thread and my edit was gone. But then I realized I made the edit in the "Comments" section, not in the copy of the thread that appeared inline.

The workaround is to just reload the page so that the views sync, but it would be neat if there was something that prevented the two copies of a thread from going out of sync after a save.

**Comment by samatcodeapprove** [comment]
That is a bug! These should definitely be synced.

**Comment by samatcodeapprove** [comment]
Pushing a fix for this now, these views will be synced!
