### ISSUE TITLE
Review on CodeApprove marker breaks placeholder

### ISSUE THREAD

**Issue by rockwotj** [codeapprove/feedback#53]
The hidden image in the description seems to break the zero state in the description area: 

When the description is:
`<a data-ca-tag href="https://codeapprove.com/pr/shortwave/shortwave/10369"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>`

I see:
![image](https://user-images.githubusercontent.com/8669100/187965186-0c944291-7d3f-460c-8b1b-4f34175e9660.png)

Instead of:
![image](https://user-images.githubusercontent.com/8669100/187965292-df289e37-3b45-4ed3-92c5-f6a89846bd2c.png)

I see the latter if I remove the anchor tag in GitHub.

**Comment by samatcodeapprove** [comment]
Pushing a fix for this now!
