### ISSUE TITLE
Copying code in a diff view copies both sides of the diff

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#54]
Sometimes I copy some code from the diff in order to suggest a rewrite. CodeApprove currently makes this hard to do because selecting text on multiple lines includes text from the left and right side of the diff instead of just a single side:

### Current behavior:

Selecting text picks up both sides of the diff

![image](https://user-images.githubusercontent.com/7783288/188737405-071a905d-9054-4806-8ae0-4ea21c29d8e2.png)

### Desired behavior

Selecting text picks up only a single side of the diff

![image](https://user-images.githubusercontent.com/7783288/188737641-2b32d14d-6e09-47db-ab84-0e056cf25b0d.png)

**Comment by samatcodeapprove** [comment]
This should now be fixed! Also cc @jdimond who asked for this.

**Comment by mtlynch** [comment]
@samatcodeapprove - Nice! I confirmed this is working as expected now.
