### ISSUE TITLE
Using a relative markdown link prevents CodeApprove from rendering text

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#57]
I'm seeing strange behavior where my comment disappears when I hit save. It comes back if I edit it, but it seems like CodeApprove can't render the preview for some reason:

https://user-images.githubusercontent.com/7783288/189216977-8f70324f-f8bc-435b-b1ce-ce68dcc14f7d.mp4

Here's the comment that triggers it:

```text
"set up your proxy" could be mistaken for configuring the proxy itself.

We also want to avoid saying "your device" when there's any ambiguity about which device we mean (proxy, TinyPilot, target device).

Suggest:

>To configure your TinyPilot device to use an HTTP proxy, [SSH to your TinyPilot](/faq/ssh-credentials), and then do the following:
```

**Comment by mtlynch** [comment]
It looks like it's the relative link:

```markdown
[SSH to your TinyPilot](/faq/ssh-credentials)
```

If I take that out, it works fine.

**Comment by samatcodeapprove** [comment]
Thanks (as always) for the specific steps to reproduce! This should be a quick fix.

**Comment by samatcodeapprove** [comment]
Deployed a build with a fix for most of this. I still think how I should render relative links is a little ambiguous (should they be relative to GitHub or CodeApprove?) but at least they will render.

**Comment by mtlynch** [comment]
>Deployed a build with a fix for most of this.

Thanks! I've verified the fix.

>I still think how I should render relative links is a little ambiguous (should they be relative to GitHub or CodeApprove?) but at least they will render.

Yeah, either is fine. They're both incorrect because the link points to something on tinypilotkvm.com, but there's no way for CodeApprove to deduce that. Just rendering something is good.
