### ISSUE TITLE
Adding a long markdown line makes a comment uneditable

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#58]
When trying to find a workaround for #57, I accidentally hit a different issue. I tried including the markdown as a blockquote:

````markdown
```markdown
To configure your TinyPilot device to use an HTTP proxy, [SSH to your TinyPilot](/faq/ssh-credentials), and then do the following:
```
````

But now I've inadvertently made the comment uneditable because it's pushed the edit dots outside of the visible part of the element:

![image](https://user-images.githubusercontent.com/7783288/189218510-ac6b81df-2897-47b8-9fcd-a44136550b3d.png)

**Comment by mtlynch** [comment]
Workaround was just to widen the browser window until the dots were visible again.

**Comment by samatcodeapprove** [comment]
Ok pushing a fix to wrap very long lines in code within comments. Ideally this would scroll, not wrap, but I couldn't get that to cooperate in some situations and hiding the edit button is worse than wrapping (IMO).

If the wrapping causes you any issues let me know and I will reopen!

**Comment by mtlynch** [comment]
Thanks! I've verified the fix.
