### ISSUE TITLE
CodeApprove summarizes line comments out of order

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#59]
When I submit a round of notes and CodeApprove posts them to the Github thread, the summary of comments is out of order. I'd expect the order to be:

* All threads from previous rounds, in ascending filename order, in ascending order of line number (PR-level comments count as line 0)
* All threads created this round, in ascending filename order, in ascending order of line number (PR-level comments count as line 0)

Instead, CodeApprove seems to sort them in random order. Within a file, the order of lines is:

- 14
- 17
- 11

![image](https://user-images.githubusercontent.com/7783288/189222499-64cef3bd-dfbe-4656-9527-5ae485ce933a.png)

**Comment by samatcodeapprove** [comment]
Just deployed a build with a fix for this.

**Comment by mtlynch** [comment]
Awesome, thanks!
