### ISSUE TITLE
CodeApprove in-app comments appear out of order

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#62]
Similar to #59 the comments at the bottom of a CodeApprove review seem to be out of order:

![image](https://user-images.githubusercontent.com/7783288/191267221-efaaaa6a-b5c2-48a7-a3d5-035596922c2c.png)

Review: https://github.com/tiny-pilot/tinypilot/pull/1079

**Comment by samatcodeapprove** [comment]
@mtlynch these are not currently intended to be in line order! They are in order by status (drafts, unresolved, then resolved) and within those status groups they are ordered by time.

You are not the first person to give feedback that you find the ordering unintuitive though. How would you like them to be ordered if I was to start over?

**Comment by mtlynch** [comment]
>You are not the first person to give feedback that you find the ordering unintuitive though. How would you like them to be ordered if I was to start over?

I'd prefer by file, then by line.

>within those status groups they are ordered by time.

Do you mean like when I created one note vs. the other within the same review? This is confusing because I think of all the notes in the review as having the same timestamp, which would be the time when I published the set of notes.

I don't mind if CodeApprove tracks when I created/modified individual notes, but I'd expect all user-visible decisions to be based on the timestamp of the note **publish** time.

**Comment by samatcodeapprove** [comment]
@mtlynch sorry I never answered here. The current order is "descending by **last comment**" which is clearly not as intuitive as I think it is! I think ordering by first comment is probably easier to grok.

**Comment by mtlynch** [comment]
>The current order is "descending by last comment" which is clearly not as intuitive as I think it is! I think ordering by first comment is probably easier to grok.

Sorry, not sure what you mean.

Are you talking about descending by line number?

**Comment by samatcodeapprove** [comment]
Nope I mean ordered by the timestamp of the last comment. So the thread with the most recent actvitiy is ordered first.

**Comment by mtlynch** [comment]
Oh, gotcha.

**Comment by samatcodeapprove** [comment]
Deploying a build now which massively simplifies how I sort comment threads. Now it's just by the timestamp of the first comment in the thread (descending). I think I was being excessively fancy before, this is probably what most people expect. Let me know if it's an improvement!

**Comment by mtlynch** [comment]
@samatcodeapprove - Does this only apply on future PRs? Looking at [this PR](https://codeapprove.com/pr/tiny-pilot/tinypilot/1079), there are three threads that occurred at the same timestamp, but the ordering is 90, 79, 66, whereas I'd expect 66, 79, 90.

![image](https://user-images.githubusercontent.com/7783288/194076513-89d1c808-616f-422c-ac8a-70e894e5b26c.png)

**Comment by samatcodeapprove** [comment]
@mtlynch at the moment later comments in the same "review" are sorted in descending order. It seems like what you want is for all comments in the same batch to be assigned the same timestamp and then for file name / line number to be the tie breaker?

**Comment by mtlynch** [comment]
>It seems like what you want is for all comments in the same batch to be assigned the same timestamp and then for file name / line number to be the tie breaker?

Yep, exactly!

My mental model of the review is that nothing really has a timestamp until I submit all comments. So CodeApprove making any decisions based on the relative timestamps *within* a round of review is unexpected.

To me, it would be sort of like if Gmail kept track of timestamps I last edited each paragraph in an email and then used that timestamp to make UI decisions. It would be confusing because I think of the "timestampable unit" as the email itself at the time I hit send and not any subparts.
