### ISSUE TITLE
Link the approved sticker to the CodeApprove review rather than the image

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#64]
Minor thing, but it's bitten me a few times:

![image](https://user-images.githubusercontent.com/7783288/192348577-708d5544-a66e-4210-965e-d349c505f454.png)

The "Approved" stamp is a link, but it just links to a larger version of the same image, which users probably never want. It would be good to link it instead to the CodeApprove review.

**Comment by samatcodeapprove** [comment]
@mtlynch 🤦 well this seems obvious in hindsight! Will do.

**Comment by samatcodeapprove** [comment]
Fixed!

**Comment by mtlynch** [comment]
Confirmed, thanks!
