### ISSUE TITLE
Reveal All button has no effect

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#66]
On [this review](https://github.com/tiny-pilot/ansible-role-ustreamer/pull/63), there's a hidden comment, but clicking "Reveal All" doesn't do anything:

https://user-images.githubusercontent.com/7783288/192864698-9b1d369f-f8ea-4e88-b07a-6f2400d6130e.mp4

**Comment by samatcodeapprove** [comment]
@mtlynch thank you for the link and the video! I will investigate.

**Comment by samatcodeapprove** [comment]
Cleaning up some old issues: I can't reproduce this anymore and the "reveal all" mechanics have been changed significantly since this was filed.

**Comment by mtlynch** [comment]
@samatcodeapprove - Yep, working for me as well!
