### ISSUE TITLE
.mjs files have no syntax highlighting

### ISSUE THREAD

**Issue by rockwotj** [codeapprove/feedback#67]
We use .mjs for some node scripts in our repo to force node to understand they use esm modules and the files aren't being syntax highlighted as javascript. This may also be a problem with .cjs

See: https://nodejs.org/api/packages.html#determining-module-system

**Comment by samatcodeapprove** [comment]
@rockwotj just deployed a build which has support for `.mjs` and `.cjs` extensions.
