### ISSUE TITLE
Commit dropdown can extend out of the viewport

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#7]
I noticed that if a commit has a long description, CodeApprove seems to let the element grow unbounded in width, so it extends out of the viewport and becomes unreadable.

Here's what I see when I click the "Head" dropdown for a PR where one of the commits has a long description:

![image](https://user-images.githubusercontent.com/7783288/178752364-eaef014d-f7ae-4d28-a1c5-730cef1a8631.png)

**Comment by hatboysam** [comment]
Thanks again for reporting! This is fixed in the latest release:
![image](https://user-images.githubusercontent.com/997280/179348269-122ea0a8-9e01-423f-8d81-825684ccb63d.png)
