### ISSUE TITLE
Make version-to-version diffs easier to use

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#70]
80% of the time, the "Show changes since my last review" is all I need. Another 10% of the time, "Show all changes" covers my needs. But there's a last 10% where I need to do fine-grained diffs between commits and CodeApprove is a little hard to use for that.

* The terms "base" and "head" are not that obvious about what's being diffed.
  * I know they're coming from git, but I think there could be more clues about the diff. Start and end? Old and new?
* The base dropdown is sorted oldest to newest, while the head dropdown is newest to oldest
* The UI allows nonsensical comparisons
  * e.g., in the commit sequence A, B, C, CodeApprove allows C as the base and A as the head, but it breaks the UI
![image](https://user-images.githubusercontent.com/7783288/196443046-7d01ddcd-8d35-454b-ba7b-8bd6f6e04638.png)

### Reviewable

I think Reviewable does this the best. The visual display makes it obvious how the ordering works, and you can do it in a single click-and-drag mouse gesture. By comparison, Gerrit and CodeApprove are each 4 clicks.

https://user-images.githubusercontent.com/7783288/196443885-2f8220cf-e9ca-41d1-8345-d559d6f914fa.mp4

### Gerrit

Gerrit is pretty similar to CodeApprove, though the arrow gives a better visual hint at the relationship between the dropdowns. They also sort the dropdowns consistently and disable invalid comparisons:

https://user-images.githubusercontent.com/7783288/196444462-f4fa70fc-4f67-4df1-a765-6a037895f9e4.mp4

**Comment by samatcodeapprove** [comment]
@mtlynch thank you for the super detailed feedback! I'd like to find something in between what I have now and the file matrix (which I find overwhelming) for CodeApprove.

**Comment by samatcodeapprove** [comment]
See https://github.com/codeapprove/feedback/issues/78, the UI should be a lot clearer now.

**Comment by mtlynch** [comment]
Cool, this is a good improvement!

My remaining nitpick is that you can still compare a commit to itself and generate an empty diff, which seems like something no user would ever actually want.

When base is at commit N, CodeApprove grays out every commit < N, but I think the more intuitive behavior is to gray out every commit <= N. This would also mean that `master` is always grayed out on the "head" dropdown.

Similarly, I'd prefer if the last commit would always be grayed out in the "base" dropdown because that always just generates an empty diff.

Also, not sure if it's related to these changes, but the list of commits now has a layout issue where the commit hashes are not vertically aligned and the dropdown scrolls both horizontally and vertically ([example](https://codeapprove.com/pr/tiny-pilot/tinypilot/1296)):

![image](https://user-images.githubusercontent.com/7783288/222055667-d15e8af6-5cab-4164-a419-eca9855e4c55.png)

**Comment by mtlynch** [comment]
@samatcodeapprove - Should I open a separate issue for the remaining items? I just want to verify you've ACKed the follow up, even if it's to wontfix.

**Comment by samatcodeapprove** [comment]
@mtlynch thanks for the bump! Reopened as `partially-complete` to track the rest

**Comment by samatcodeapprove** [comment]
Deploying a fix for the remaining items now!

**Comment by mtlynch** [comment]
Cool, thanks! Fix verified.
