### ISSUE TITLE
CodeApprove duplicates review-level threads

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#72]
On [this review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1146), CodeApprove is duplicating a review-level discussion thread:

![image](https://user-images.githubusercontent.com/7783288/196685304-cd562baf-8ad4-4bf0-8f63-44011c9ddf44.png)

From the [history on Github](https://github.com/tiny-pilot/tinypilot/pull/1146#pullrequestreview-1147168764), it looks like the reviewer:

1. Made a review-level comment
2. Approved
3. Published the review
4. Added a line-level comment
5. Published the line-level comment

It looks like somehow CodeApprove got confused by that flow and duplicated his review-level comment starting with "Shall we also move..."

**Comment by jotaen4tinypilot** [comment]
To clarify, the course of events was:

1. I (the reviewer) wrote a line-level comment, but forgot to submit (i.e. click the “Add to review” button)
2. I then wrote a review-level comment
3. I published the review
4. I noticed that the line-level comment wasn’t included, so I submitted it and published the review again

It would have been cool if CodeApprove had warned me that there is an un-submitted line-level comment.

But regardless of that, I agree it shouldn’t have published the review-level comment again.

**Comment by samatcodeapprove** [comment]
Thank you both for laying out how this happened! I will try to reproduce this.

**Comment by samatcodeapprove** [comment]
(commenting for myself) investigating here a little bit and this is not just a frontend bug, the comment in question got into the database twice with different timestamps:

1. Wed Oct 19 2022 09:16:37
2. Wed Oct 19 2022 09:16:56

So for some reason, it was submitted twice even when @jotaen4tinypilot obviously did not intend to.

**Comment by samatcodeapprove** [comment]
🤦 well this is a simple one! The "finish review" dialog doesn't clear its state after submitting, so if you submit back-to-back reviews without leaving the page it's really easy to send the same review-level comment twice.

Fix for this going out now!

**Comment by jotaen4tinypilot** [comment]
Awesome, thanks for sorting that out!
