### ISSUE TITLE
CodeApprove renders Unicode double quotes incorrectly

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#73]
On this review: https://codeapprove.com/pr/tiny-pilot/tinypilot/1153

The text is:

```text
For evolving our database schema over time, we follow the idea of “evolutionary
database design”
```

Github rendering:

![image](https://user-images.githubusercontent.com/7783288/196948389-52023e12-8f68-4878-8c27-42e3fee135ae.png)

CodeApprove rendering:

![image](https://user-images.githubusercontent.com/7783288/196948460-aed90ef5-896b-473f-90ec-f7df575e5fdc.png)

**Comment by samatcodeapprove** [comment]
@mtlynch I̵ ̶d̷o̴n̸'̶t̵ ̶s̵e̸e̶ ̴t̶h̵e̴ ̴p̴r̴o̷b̷l̸e̷m̸!̷ 😄

**Comment by samatcodeapprove** [comment]
Just pushed a fix for this issue, thanks for flagging!

**Comment by mtlynch** [comment]
@samatcodeapprove - Confirmed, thanks!
