### ISSUE TITLE
Show All Changes breaks Collapse All / Expand All buttons

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#74]
I noticed that when I switch between "Show all changes" and "Since my last review," the Collapse All / Expand All buttons behave unexpectedly, sometimes going completely non-functional:

https://user-images.githubusercontent.com/7783288/196952146-cfe947aa-da5e-4ed8-b241-24898f224310.mp4

There are two bugs here:

* The more obvious one is that the expand all / collapse all buttons should never cease to function
* The more subtle one is that I'd prefer CodeApprove to remember expand all / collapse all state when I switch views
  * i.e., if I have all diffs expanded in "Show All Changes" view, CodeApprove should assume I want to keep them expanded when I switch to "Since my last review" view

**Comment by samatcodeapprove** [comment]
@mtlynch thanks for the video! That's super clear

**Comment by mtlynch** [comment]
@samatcodeapprove - Just wanted to bump this one as this is the most frequent CodeApprove bug I hit in my normal flow.

My manual workaround to #61 is to manually expand diffs at the start of the review, but this bug breaks that workaround because it causes the "Expand All" button to stop functioning.

**Comment by samatcodeapprove** [comment]
Thanks for bumping this! I'll take another look

**Comment by samatcodeapprove** [comment]
Just implemented a fix for this and it should be available in ~10 minutes! Let me know if you still see bad behavior here.

**Comment by mtlynch** [comment]
Thanks! Will do.
