### ISSUE TITLE
Non-existing “file” appears in CodeApprove review

### ISSUE THREAD

**Issue by jotaen4tinypilot** [codeapprove/feedback#75]
In this PR https://github.com/tiny-pilot/tinypilot/pull/1161, Github shows 9 files changed:

<img width="346" alt="Screenshot 2022-10-21 at 17 22 23" src="https://user-images.githubusercontent.com/83721279/197231749-0bbb3408-8c8c-4356-ab2d-45fd8ed01190.png">

On CodeApprove, however, there is a tenth file, that reports a filename change of a non-existing file. Instead, the “file name” is a seemingly random piece of text from the change set:

<img width="799" alt="Screenshot 2022-10-21 at 17 21 33" src="https://user-images.githubusercontent.com/83721279/197232041-8f147bc3-8a55-4ca1-a55a-b5776acc37dc.png">

**Comment by samatcodeapprove** [comment]
@jotaen4tinypilot whoah that's really really strange, I have never seen the diff parser have an issue like that before. Thanks for flagging the specific PR

**Comment by samatcodeapprove** [comment]
A fix for this issue has been released, I had to upgrade our diff parser library. 

TIL that python comments (`---`) look a lot like diff headers (`+++`, `---`)!
