### ISSUE TITLE
Allow comments on binary files

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#76]
I'm reviewing a PR that includes image files. CodeApprove allows me to mark the image file as reviewed, but it doesn't allow me to attach comments to the file. I'd like to be able to comment on binary files sometimes, especially images and videos.

I don't need anything fancy like commenting on a particular part of the image/video. Just being able to make file-level comments would be sufficient.

**Comment by samatcodeapprove** [comment]
Thanks for requesting this! This has been a long-awaited feature request but I forgot to migrate it to GitHub

**Comment by samatcodeapprove** [comment]
You can now leave comments on whole files, including images and other binary files!
https://www.loom.com/share/fb18cae8f9a6437184b6fa1130ef2c17

**Comment by mtlynch** [comment]
Awesome, that looks great. Thanks for adding this!
