### ISSUE TITLE
Confusing commit select order

### ISSUE THREAD

**Issue by tstirrat** [codeapprove/feedback#78]
Showing the commits in reverse order on the second commit selector always confuses me.

<img width="505" alt="Screen Shot 2022-10-29 at 6 52 56 AM" src="https://user-images.githubusercontent.com/702990/198721156-b65df6d5-5f7d-4fb4-bbe6-28a60ccec237.png">

Suggestion:

Fade out the omitted commits, always use the same order:

<img width="468" alt="Screen Shot 2022-10-29 at 7 00 27 AM" src="https://user-images.githubusercontent.com/702990/198722306-48b4843b-4d70-4dc8-aec2-d58818124da6.png">

If you did this on _both_ selectors, it would still be a huge benefit.

💡 **Future:** Ideally you could make it a single dropdown with 2 clicks setting the from and 2 respectively, but I think the above order and visual changes will drastically improve the UX and is much less work.

**Comment by tstirrat** [comment]
Quick 1 min idea: You could even add a little left border or faint blue background that moves as you hover over the end  to show this is an inclusive selection.

<img width="462" alt="Screen Shot 2022-10-29 at 7 12 59 AM" src="https://user-images.githubusercontent.com/702990/198724239-7b287c07-22b9-4d31-8ea7-594f72c8c4a9.png">


<img width="458" alt="Screen Shot 2022-10-29 at 7 14 58 AM" src="https://user-images.githubusercontent.com/702990/198724216-a9e36991-ba97-4cee-9494-10011616bdaf.png">

**Comment by samatcodeapprove** [comment]
@tstirrat you are a legend! These designs are really nice and they're inspiring me to do something about this UI.

**Comment by samatcodeapprove** [comment]
Note to self, this is very overlapping with https://github.com/codeapprove/feedback/issues/70

**Comment by samatcodeapprove** [comment]
About to deploy some improvements here, incorporating a lot of your ideas. Here's a preview:
https://www.loom.com/share/945b3e87942f456fbd8d0dc49b1f0246

**Comment by tstirrat** [comment]
Omg yes! Looks great!
