### ISSUE TITLE
CodeApprove reports a PR approved, Github says it's pending approval

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#80]
We just ran into an unexpected blocker with a PR we reviewed through CodeApprove.

1. Developer sent out PR for review
2. Reviewer 1 sends notes, doesn't mark PR as approved
3. Reviewer 2 (me) chimes in with a suggestion, doesn't mark PR as approved
4. Developer addresses feedback, marks all issues as resolved
5. Reviewer 1 marks PR as approved

## Expected behavior

CodeApprove changes approvals in Github to all approved

## Actual behavior

CodeApprove changes approvals in Github for Reviewer 1 as approved, Reviewer 2 (me) is still marked as "Changes requested," which blocks the PR from being merged.

## Screenshots

![image](https://user-images.githubusercontent.com/7783288/200010404-18f52279-3ceb-46c2-9799-86d360217c8e.png)

![image](https://user-images.githubusercontent.com/7783288/200010497-c2c40265-15bb-49f7-b164-bbd8a5310f2e.png)

![image](https://user-images.githubusercontent.com/7783288/200010573-6c3ca435-c49b-4c79-976d-c67f685b37c2.png)

**Comment by samatcodeapprove** [comment]
@mtlynch yikes! I'll see what the logs say. There's also a link at the bottom of every CodeApprove PR page which lets you re-sync the PR in case things get out of whack like this. Mind seeing if that helps here (assuming it's still in this state)?

**Comment by samatcodeapprove** [comment]
@mtlynch oh wow I just realized this was from 11 days ago 🤦 which means you definitely worked around this. Sorry I let this slip through my inbox! Not sure what happened.

**Comment by mtlynch** [comment]
@samatcodeapprove - That's okay. Yeah, I just approved it to unblock. We haven't seen it again, but I'm also not sure if we've created the same conditions. I'll bump the thread if we see this again.

**Comment by rockwotj** [comment]
We've seen this frequently too. Hitting the `sync` button at the bottom left in codeapprove fixes it.

**Comment by mtlynch** [comment]
We just hit this again on https://github.com/tiny-pilot/ustreamer-debian/pull/6 but re-syncing didn't fix it.

**Comment by samatcodeapprove** [comment]
@mtlynch thanks for letting me know! Seems like you got it fixed for that PR by re-approving? I'll check out the logs.

**Comment by mtlynch** [comment]
The PR already had approval from one other reviewer, but I had commented, so it was blocking the review until I approved as well.

The behavior we want is that one approval is sufficient even if multiple people commented on the PR.

**Comment by mtlynch** [comment]
We just hit this again on https://github.com/tiny-pilot/tinypilot/pull/1458

The re-sync workaround didn't work.

**Comment by samatcodeapprove** [comment]
Hmmm thanks for reporting I’ll take a look!

**Comment by jdeanwallace** [comment]
We just hit this again on https://github.com/tiny-pilot/tinypilot/pull/1469

The re-sync workaround didn't work.

**Comment by samatcodeapprove** [comment]
@jdeanwallace thanks for bumping this again. Just want to lay out what I see.

On CodeApprove:

1. mtlynch reviewed (no approval)
2. jotaen4tinypilot reviewed (no approval)
3. mtlynch reviewed (no approval)
4. mtlynch reviewed (no approval)
5. mtlynch reviewed (approval)

On GitHub:

1. mtlynch requested changes
2. jotaen4tinypilot requested changes
3. mtlynch requested changes
4. mtlynch requested changes
5. mtlynch requested changes (with pending approval)
6. mtlynch auto-approved

So the problem here is that jotaen4tinypilot's review is still listed as "requested changes" which blocks you on GitHub. I can make a change so that hanging reviews like that are dismissed.

**Comment by samatcodeapprove** [comment]
@jdeanwallace this should not happen any more, thanks for providing a clear case!

**Comment by jdeanwallace** [comment]
Thanks @samatcodeapprove, looking forward to forgetting about this thread 😆

**Comment by mtlynch** [comment]
@samatcodeapprove - Just to clarify, the functionality we're hoping for is that CodeApprove unblocks the PR when there's >=1 approval and 0 unresolved threads.

In other words, if five teammates add drive-by comments, and one person gives approval, we want the PR to be considered approved based on the one approval and not wait for any of the other five teammates to approve (as long as their threads are resolved).

Is that CodeApprove's new behavior?

**Comment by samatcodeapprove** [comment]
@mtlynch that is the intended behavior! Let me know if you're not seeing this.

**Comment by mtlynch** [comment]
@samatcodeapprove - Gotcha, thanks! We'll bump the thread if we hit something in the future that's unexpected.
