### ISSUE TITLE
CodeApprove can't see a private repo, even though it's visible in settings

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#81]
I have a private repo I've configured to use with CodeApprove:

![image](https://user-images.githubusercontent.com/7783288/201704207-09de6f3b-9240-421d-8a88-fd69c94b0889.png)

We recently created a PR, and CodeApprove added the proper label:

![image](https://user-images.githubusercontent.com/7783288/201704454-5bc20553-1ca2-4710-9d6d-da6b807dc8a4.png)

But it didn't update the PR description with a CodeApprove badge, and attempting to view the PR from CodeApprove fails:

![image](https://user-images.githubusercontent.com/7783288/201704758-1dae8a32-a444-4d71-be66-a068f094d683.png)

**Comment by samatcodeapprove** [comment]
Yikes that's not good, I will do some digging but in the meantime you might want to try "turning it off and back on again":

- Sign in/out of CodeApprove
- Remove/re-add the repo through your CodeApprove settings

**Comment by samatcodeapprove** [comment]
@mtlynch actually before you try those nuclear options, does removing and re-adding the label to the PR work? As far as I can tell CodeApprove has no problem connecting to this repo (I see PRs 116 through 139) but 140 seems to be missing.

**Comment by mtlynch** [comment]
@samatcodeapprove - Ah, removing and re-adding the label fixed it. Nothing in the logs about PR 140 before that?

**Comment by samatcodeapprove** [comment]
@mtlynch unfortunately this escaped my logging, it must have failed very early (or not reached me at all, but that feels unlikely). I have spent the night beefing up logging at the root level to catch this in the future!

Going to close for now since I can't actually investigate this with the data I have.

**Comment by mtlynch** [comment]
@samatcodeapprove - This happened again on a public repo, though this time the label didn't get added at all:

https://github.com/tiny-pilot/tinypilot/pull/1198
