### ISSUE TITLE
Confirmation or undo of comment deletion?

### ISSUE THREAD

**Issue by jotaen4tinypilot** [codeapprove/feedback#82]
I just wanted to edit a code review comment, but since the `Edit` and `Delete` options in the dropdown menu are right next to each other, I accidentally clicked on `Delete` instead of `Edit`. My comment disappeared instantly, without an obvious possibility to restore it. Therefore, I had to rewrite it entirely.

<img width="177" alt="Screenshot 2022-11-17 at 14 00 57" src="https://user-images.githubusercontent.com/83721279/202453626-357f8253-4731-447d-a377-9884e88e4ce3.png">

It would be cool if there either was a confirmation preceding the deletion, or an obvious way to restore the comment afterwards (like a “grace period”, where it shows a “restore” button for like 10 seconds).

**Comment by samatcodeapprove** [comment]
Deploying a fix for this now!
