### ISSUE TITLE
Make `golang` an alias for `go` in code snippets

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#84]
Minor feature request. It would be good if CodeApprove did syntax highlighting for both `golang` and `go` language quotes in fenced code snippets. Currently, only `go` works.

By comparison, on Github, both `golang` and `go` get syntax highlighting:

```golang
var s string
if true {
  s := "Hello, world!"
}
```

```go
var s string
if true {
  s := "Hello, world!"
}
```

**Comment by samatcodeapprove** [comment]
@mtlynch thanks for noticing! Should be a very quick fix

**Comment by samatcodeapprove** [comment]
Pushing this now!

**Comment by mtlynch** [comment]
Awesome, thanks!
