### ISSUE TITLE
CodeApprove can't render "Since my last review"

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#85]
I've run into an odd scenario in CodeApprove where it seems confused about the ordering of reviews and commits.

https://codeapprove.com/pr/tiny-pilot/tinypilotkvm.com/881

Here are the commits:

![image](https://user-images.githubusercontent.com/7783288/209401107-7030fb0a-b114-40b4-9283-015418bad3c0.png)

I gave my last review on this PR in CodeApprove on 2022-12-20 after commit `5e1120d`. CodeApprove shows the correct time for this review:

![image](https://user-images.githubusercontent.com/7783288/209401471-891f526c-abc4-4ad0-8886-d26fa0fc84e5.png)

In CodeApprove, if I select "Show: Since my last review", it sets both the base and head to `5e1120d` even though  `5e1120d` was on 2022-12-20 @ 3:20 PM EST:

![image](https://user-images.githubusercontent.com/7783288/209401247-64515665-85f4-4efd-aa81-0c3bad39dce2.png)

I'd expect CodeApprove to set base to `5e1120d` and head to `dfdbcae` since `dfdbcae` is the only commit that occurred after my last review. If I manually choose those commits, it shows the expected result, but for some reason, CodeApprove can't figure out the correct diff to show.

**Comment by samatcodeapprove** [comment]
@mtlynch thanks for reporting this, I will take a look.

**Comment by samatcodeapprove** [comment]
Ok I think I found the fix here, pushing this. It's a little hard to be 100% sure (since I don't have the ability to time-travel debug and see what you saw at that exact moment) so let me know if anything like this happens again!

**Comment by mtlynch** [comment]
Thanks!
