### ISSUE TITLE
Long links cause horizontal scrolling in the review comment box

### ISSUE THREAD

**Issue by rockwotj** [codeapprove/feedback#87]
See:

![CleanShot 2023-01-06 at 09 55 21](https://user-images.githubusercontent.com/8669100/211049096-e3894327-6df9-4f03-9423-83a362c8b328.png)

**Comment by samatcodeapprove** [comment]
@rockwotj well ... that's a bug! Will fix.

**Comment by samatcodeapprove** [comment]
Pushing a fix now!
