### ISSUE TITLE
Add syntax highlighting for bash scripts

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#9]
CodeApprove doesn't do any syntax highlighting for bash scripts, which makes them a bit harder to review:

![image](https://user-images.githubusercontent.com/7783288/179052049-386ea65e-67e5-44f0-81a5-c01cbfd05087.png)

Github for comparison:

![image](https://user-images.githubusercontent.com/7783288/179052181-7ec66bc3-b643-4a0a-b342-f04eb084091e.png)

**Comment by hatboysam** [comment]
Good call out! Will add.

**Comment by mtlynch** [comment]
@hatboysam - Thanks, looks great!
