### ISSUE TITLE
Since my last review: Puts comments into a greyed out state

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#91]
On round 2 of a review, if I change the view to "Since my last review" and then add a new comment, the comment appears in a greyed out state.

![image](https://user-images.githubusercontent.com/7783288/214956166-1031e169-7b13-4e8a-9436-3b37a458d4e3.png)

If I reload the page, the comment disappears from the "Since my last review" view and only appears in "All changes."

### Repro

1. Reviewer receives a PR
2. Give a first round of notes in CodeApprove
3. Author makes revisions and responds to notes
4. Reviewer changes view to "Since my last review"
5. Reviewer adds a new comment

Expected result: New comment appears normally

Actual result: New comment appears greyed out

https://user-images.githubusercontent.com/7783288/214956660-a1999fbd-57b2-4cf9-812d-3e541644a619.mp4

**Comment by samatcodeapprove** [comment]
@mtlynch as always, thanks for the thorough report. That's a pretty bad bug, I'll try and solve this ASAP.

**Comment by samatcodeapprove** [comment]
@mtlynch I just deployed a fix for this, should be live in ~10 minutes. Thanks for helping me pinpoint this so exactly!

**Comment by mtlynch** [comment]
@samatcodeapprove - Excellent, thanks!
