### ISSUE TITLE
Update PR page title to include name of PR

### ISSUE THREAD

**Issue by jwngr** [codeapprove/feedback#93]
Feature request: Update the title tag with the PR name like GitHub does

If you have a bunch of CA tabs open, it looks like this and it's impossible to know which one has which PR:
<img width="657" alt="Screenshot - 2023-03-01 at 18-14-20@2x" src="https://user-images.githubusercontent.com/4149793/222313309-28287a1e-afb2-4bd3-8b81-b5ede34a8777.png">

These are the same PRs in GitHub tabs, which make it easier to find:
<img width="654" alt="Screenshot - 2023-03-01 at 18-14-24@2x" src="https://user-images.githubusercontent.com/4149793/222313299-fa4b8db7-6cb5-448a-beb6-54acf45a2e72.png">

**Comment by samatcodeapprove** [comment]
@jwngr thanks for reminding me! This actually used to work and it stopped, so I consider this a bug,

**Comment by samatcodeapprove** [comment]
Pushing a fix for this now!
