### ISSUE TITLE
Large PNG image fails to render in PR

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#94]
CodeApprove fails to render a large PNG image in [a PR](https://codeapprove.com/pr/tiny-pilot/tinypilotkvm.com/953):

![image](https://user-images.githubusercontent.com/7783288/229169750-6cd16dea-b310-428d-ac0b-21fcca81e6c0.png)

Inspecting the source, I see this tag for that image:

```html
<img data-v-340c15f2="" src="data:image/png;none, " class="block m-auto">
```

From Github it looks fine:

![image](https://user-images.githubusercontent.com/7783288/229169953-8eaed287-f687-4173-b2b9-e9c29685ca4e.png)

I notice that it's a very large image (1.74M), and CodeApprove seems to be inlining the image as base64, so maybe that's messing things up.

Here's the problem image as it appears in the source tree: https://p.tinypilotkvm.com/-UyhkwSMqFC/export-settings.png

**Comment by samatcodeapprove** [comment]
@mtlynch thanks for reporting! I suspect GitHub has a limit (and I bet it's 1MB) above which I need to make a separate request for file content instead of getting it inline in the normal "pull request changes" API request. This shouldn't be too hard to fix.

**Comment by samatcodeapprove** [comment]
@mtlynch deploying a fix for this now!

**Comment by mtlynch** [comment]
Confirmed, thanks!
