### ISSUE TITLE
Light Mode

### ISSUE THREAD

**Issue by cghague** [codeapprove/feedback#96]
It would be great if a light mode option could be added to CodeApprove!

I appreciate that dark mode is a popular choice for many users, but, unfortunately, it can be problematic for others, myself included. My eyesight means that I struggle to use dark interfaces and prolonged usage becomes painful due to eyestrain. A light mode would be a welcome accessibility improvement.

Would this be something you could add? Thanks!

**Comment by samatcodeapprove** [comment]
@cghague thanks for the feedback! Funny enough I am actually a light mode person myself, but in my experience _most_ devs use dark mode tools so I decided to target what I thought would be the most popular option for v1.

To be honest: yes I will do this one day, and no it will not be very soon. The app has not been built in a "themeable" way and so this would amount to a nearly complete re-design. But I will definitely keep this on the list!

**Comment by mtlynch** [comment]
@samatcodeapprove - Is there any possibility of something that's like 20% effort, 80% benefit solution before the real solution is available? Like even if we have to flip it on with URL query params (e.g. `codeapprove.com/pr/tiny-pilot/tinypilot-pro/859?light-hack=1` and even if it's kind of ugly but still usable, that would be a good improvement.

**Comment by samatcodeapprove** [comment]
@mtlynch I definitely will look into it!

**Comment by mtlynch** [comment]
@samatcodeapprove - Any update here? This is something we'd still really love to see, even if we have to turn it on via URL query params.

**Comment by samatcodeapprove** [comment]
@mtlynch @cghague well ... that wasn't as hard as I thought! Put together a first pass at light mode today, you can enable it in the settings:
https://www.loom.com/share/92c0a3444e4141f58e6c30a704edf0ef

I am sure there are spots I missed (every color in the app has a chance at being "wrong" now) so please file new issues if you find areas where things don't look right in either light or dark mode after this change.

Will be releasing this soon, issue will auto-close when I do.
