### ISSUE TITLE
Make it easier to go from Github PR URL to associated CodeApprove URL

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#98]
It would be handy if there was a place in CodeApprove to paste the Github URL and CodeApprove pulls up the associated CodeApprove review.

Reviewable has this at the top of their dashboard:

![image](https://github.com/codeapprove/feedback/assets/7783288/dc703542-44a8-4f66-a642-e237e891ef37)

One other partway implementation that I suspect would be easy to implement is to let CodeApprove handle Github-style routes. So, for example, a Github PR URL can look like one of these:

* `https://github.com/tiny-pilot/tinypilot/pull/1360`
* `https://github.com/tiny-pilot/tinypilot/pull/1360/commits`
* `https://github.com/tiny-pilot/tinypilot/pull/1360/checks`
* `https://github.com/tiny-pilot/tinypilot/pull/1360/files`

It would be handy if I could copy the route from Github and paste it after the `/pr` part of the CodeApprove URL, and CodeApprove would figure it out. Like

* `https://codeapprove.com/pr/tiny-pilot/tinypilot/pull/1360` -> `https://codeapprove.com/pr/tiny-pilot/tinypilot/1360`
* `https://codeapprove.com/pr/tiny-pilot/tinypilot/pull/1360/commits` -> `https://codeapprove.com/pr/tiny-pilot/tinypilot/1360`
* etc.

**Comment by samatcolumn** [comment]
These are all good ideas! I like the idea of handling GH routes after the /pr/ ... probably should have done that from the start.

**Comment by samatcodeapprove** [comment]
These are all good ideas! I like the idea of handling GH routes after the
/pr/ ... probably should have done that from the start.

**Comment by samatcodeapprove** [comment]
@mtlynch this has been deployed. If you replace `github.com` with `codeapprove.com` in the URL for a PR, you'll end up on the CodeApprove PR page.

Note: the PR must already exist in CodeApprove, this does not automatically create it.

**Comment by mtlynch** [comment]
Confirmed, thanks!
